ALTER SEQUENCE users.us_id RESTART WITH 1;
DELETE FROM users;

DELETE FROM b01_PERFIL;

ALTER SEQUENCE b02_SERVICO.id RESTART WITH 1;
DELETE FROM b02_SERVICO;

DELETE FROM b03_PF_SE;

DELETE FROM b04_US_PF;

DELETE FROM b05_PESSOA;

DELETE FROM b07_PROFESSOR;

DELETE FROM b09_ALUNO;

DELETE FROM b10_ADMINISTRADOR;

DELETE FROM b11_DISCIPLINA;

ALTER SEQUENCE b12_MODULO.mod_id RESTART WITH 1;
DELETE FROM b12_MODULO;

ALTER SEQUENCE b13_TRILHA.tri_id RESTART WITH 1;
DELETE FROM b13_TRILHA;

DELETE FROM b14_CURRICULO;

DELETE FROM b15_REL_AL_CUR;

DELETE FROM b16_REL_CUR_TRI;

DELETE FROM b17_TR_MO;

DELETE FROM b18_REL_DIS_MOD;

DELETE FROM b19_PLANEJA;

DELETE FROM b20_MINISTRA;

DELETE FROM b21_ADMINISTRA;

DELETE FROM b22_OFERECIMENTO;

DELETE FROM b23_CURSA;